version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=roomsync_db
      - POSTGRES_USER=roomsync_user
      - POSTGRES_PASSWORD=roomsync_password

  backend:
    build: 
      context: ./RoomSync Backend main
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 room_booking_system.wsgi:application"
    volumes:
      - ./RoomSync Backend main:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=*,localhost,127.0.0.1
      - DB_NAME=roomsync_db
      - DB_USER=roomsync_user
      - DB_PASSWORD=roomsync_password
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  frontend:
    build:
      context: ./RoomSync..-main
    ports:
      # Map localhost:80 to container:80
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
